### ISSUE TITLE
Not possible to build with Xamarin Forms release build

### ISSUE THREAD

**Issue by alexanderzuban** [oleg-st/ZstdSharp#3]
It is not possible to build xamarin forms release build. 
Works fine with debug(Linking to "None"), but Release Build(Linking is set to "Sdk Assemblies Only") failing with the error
`
Error		Mono.Linker.MarkException: Error processing method: 'System.Void* ZstdSharp.UnsafeHelper::memcpy(System.Void*,System.Void*,System.UInt64)' in assembly: 'ZstdSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void InlineMethod.InlineAttribute::.ctor(System.Boolean)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	App1.Android			

[App1.zip](https://github.com/oleg-st/ZstdSharp/files/7269013/App1.zip)
`

**Comment by oleg-st** [comment]
I think it's fixed in 0.5.1

**Comment by alexanderzuban** [comment]
It works! Thank you!
