### ISSUE TITLE
Does not support compressing data larger than 2 GiB

### ISSUE THREAD

**Issue by hez2010** [oleg-st/ZstdSharp#40]
It will throw if you are trying to compress data larger than 2 GiB, even if you are using `Stream` APIs.

```
Unhandled exception. System.IO.IOException: Stream was too long.
   at ZstdSharp.CompressionStream.WriteInternal(ReadOnlySpan`1 buffer, ZSTD_EndDirective directive)
   at ZstdSharp.CompressionStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
```

**Comment by hez2010** [comment]
Never mind. It turns out to be an issue of `MemoryStream`. After changing the output stream to a `FileStream` it works fine.
